### ISSUE TITLE
Generated file name is obscure

### ISSUE THREAD

**Issue by pseusys** [rlespinasse/drawio-export-action#21]
## Issue
Suppose I have a directory `assets` with file `diagram.drawio` in it.  
I have to convert the `diagram.drawio` to `.png` in the same directory.  
I used the following configuration:
```yaml
- name: Render .drawio Files
  uses: rlespinasse/drawio-export-action@v2
  with:
      format: png
      path: assets
      output: assets
      action-mode: all
```
But apparently there is no such file as `assets/diagram.png`.

## Solution
I would like the file `assets/diagram.png` to be generated as a result of described above example.

## Alternatives
Finally I found another action, that didn't work either, but at least it could be patched:
```yaml
- name: Render .drawio Files
  uses: docker://ghcr.io/racklet/render-drawio-action:v1
  with:
      args: '"--sub-dirs=docs/assets" "--formats=png"'
```
However this action afaik is outdated and uses deprecated lib. I would love to use your action.
If I only knew how...

**Comment by pseusys** [comment]
There are few important things you should know this to become clear to you:
1. Path passed with `output` parameter is __relative to the `path`__! That's not stated in documentation, neither it is obvious.
2. Considering my example, all of my files were be named: "[FILENAME]-Page-N.png", where:
    1. [FILENAME] is the original file name (without extension).
    2. Page is literally the word page (OR its translation to some language, in my case it was sometimes english sometimes russian).
    3. N is the page number. Regularily, for ordinary `.drawio` diagrams, it will be 1.

Finally I had to use the following steps combination in order to achieve my original goal:
```yaml
- name: Render .drawio Files
  uses: rlespinasse/drawio-export-action@v2
  with:
      format: png
      path: assets
      output: .
      action-mode: all

# WARNING! This step implies all of the .drawio sources are ONE PAGE diagrams only!
- name: Rename Files
    run: for f in assets/*.png; do mv "$f" "$(echo "$f" | sed 's/-.\+-[0-9]\+//g')"; done
```
